Fix for issue #815
man-group/arctic pull request #881
Opened 2021-01-13 10:52 UTC by enricodetoma

I produced a fix for the import errors/deprecations in issue #815.
With a recent version of Pandas, importing Panel results in an error, not just a future warning.
Please have a look at it.

2021-01-22 13:48 UTC, bmoscon commented
@enricodetoma seems reasonable. Can you put in a pytest skip for the tests that use panels? You should be able to skip the tests based on the version of pandas

2021-01-23 00:54 UTC, bmoscon approved these changes

2021-01-23 00:56 UTC, bmoscon requested changes

2021-01-23 00:56 UTC, bmoscon commented on tests/unit/store/test_pandas_ndarray_store.py
this file is missing the pytest import

2021-01-23 00:57 UTC, bmoscon commented
@enricodetoma looks like just that import is missing then I can merge this

2021-01-23 08:27 UTC, enricodetoma commented
Sorry I forgot to check the Travis build for any residual errors after my commits...

2021-01-23 16:59 UTC, bmoscon approved these changes

2021-01-23 17:02 UTC, bmoscon approved these changes

2021-01-24 18:33 UTC, bmoscon commented
@jamesblackburn @TomTaylorLondon @shashank88 - this looks good to merge on my end - shouldn't break anything but allows users to use newer versions of pandas (the caveat being no more panel support when running a later version of pandas)

2021-01-26 00:14 UTC, bmoscon approved these changes

2021-01-26 00:14 UTC, merged